apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-deployment
spec:
  selector:
    matchLabels:
      app: order
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: order
    spec:
      containers:
      - name: order
        image: harbor.yuanzhibin.com/library/order:<BUILD_TAG>
        ports:
        - containerPort: 80
