apiVersion: apps/v1
kind: Deployment
metadata:
  name: account-deployment
spec:
  selector:
    matchLabels:
      app: account
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: account
    spec:
      containers:
      - name: account
        image: jackbuer123/account:<BUILD_TAG>
        ports:
        - containerPort: 80
