apiVersion: apps/v1
kind: Deployment
metadata:
  name: storage-deployment
spec:
  selector:
    matchLabels:
      app: storage
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: storage
    spec:
      containers:
      - name: storage
        image: harbor.yuanzhibin.com/library/storage:<BUILD_TAG>
        ports:
        - containerPort: 80
