apiVersion: apps/v1
kind: Deployment
metadata:
  name: logic-deployment
spec:
  selector:
    matchLabels:
      app: logic
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: logic
    spec:
      containers:
      - name: logic
        image: jackbauer123/logic:${env.BUILD_NUMBER}
        ports:
        - containerPort: 80
