apiVersion: apps/v1
kind: Deployment
metadata:
  name: logic-deployment
spec:
  selector:
    matchLabels:
      app: logic
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: logic
    spec:
      containers:
      - name: logic
        image: harbor.yuanzhibin.com/library/logic:<BUILD_TAG>
        ports:
        - containerPort: 8104
